### ISSUE TITLE
Ошибка сборки образа ISO

### ISSUE THREAD

**Issue by tutlo-kirov** [alt-cloud/getacos#16]
При выполнении инструкции https://github.com/alt-cloud/getacos/blob/main/docs/make_iso.md на команде
sudo ./getacos/ostree/bin/rootfs_to_repo.sh $OSTREE_BRANCH out/acos-latest-x86_64.tar $MAIN_REPO out 
возникает ошибка 
Date for version: 20210907
Synchronizing state of sshd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable sshd
Synchronizing state of docker.service with SysV servicpre script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable docker
Created symlink /etc/systemd/system/local-fs.target.wants/ostree-remount.service → /lib/systemd/system/ostree-remount.service.
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
usermod: группа «root» не существует
usermod: группа «wheel» не существует

**Comment by keremet** [comment]
Исправлено в https://github.com/alt-cloud/getacos/commit/ed15ad369b4f44c34f39e9d2e263a80477cc7295
