### ISSUE TITLE
Ошибка сборки ISO образа

### ISSUE THREAD

**Issue by tutlo-kirov** [alt-cloud/getacos#23]
При выполнении инструкции https://github.com/alt-cloud/getacos/blob/main/docs/make_iso.md возникает ошибка на этапе выполнения команды сборки архива acos.tar 

make -C mkimage-profiles DEBUG=1 APTCONF=$PWD/apt/apt.conf.sisyphus.x86_64 IMAGEDIR=$PWD/out vm/acos.tar

make: вход в каталог «/home/gleb/acos_build/mkimage-profiles»
** goal: vm/acos.tar
** ARCH: x86_64
07:20:53 cleaning up 
07:20:54 initializing BUILDDIR: build/
07:20:55 preparing distro config: build/distcfg.mk
07:21:04 starting image build: tail -f build/build.log
07:21:43 failed, see log above
E: Couldn't find package acos-config
make[1]: *** [lib/build.mk:73: build-image] Ошибка 2
make: *** [Makefile:42: vm/acos.tar] Ошибка 1
make: выход из каталога «/home/gleb/acos_build/mkimage-profiles»

**Comment by keremet** [comment]
пакет acos-config уже доступен на ftp. Ошибка больше не должна проявляться
