### ISSUE TITLE
При установке ACOS требуется индикация распаковки

### ISSUE THREAD

**Issue by tutlo-kirov** [alt-cloud/getacos#6]
![Баг про индикацию распаковки](https://user-images.githubusercontent.com/66792152/131561686-455ce280-8647-441b-8359-a86713383edb.png)
Этап распаковки длился достаточно долго, и было непонятно, зависла система или идёт процесс распаковки.

**Comment by keremet** [comment]
Индикация добавлена в данном коммите http://git.altlinux.org/gears/s/startup-installer-acos.git?p=startup-installer-acos.git;a=commitdiff;h=0338c56c0ab1745b7efe1e774926e9ae05f2ca7a
